steps:
  - id: 'Terraform Infrastructure init'
    # name: 'hashicorp/terraform:1.0.0'
    # entrypoint: 'sh'
    # args : ["terraform", "-chdir=./cluster-deploy", "init"]
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args: 
    - '-c'
    - terraform -chdir=./app-deploy init
#   - id: 'Terraform Infrastructure set workspace'
#     name: 'hashicorp/terraform:1.0.0'
#     entrypoint: 'sh'
#     args : ["-c", "terraform", "-chdir=./cluster-deploy", "workspace", "select", "$($BRANCH_NAME)"]
#   - id: 'Terraform Infrastructure apply'
#     name: 'hashicorp/terraform:1.0.0'
#     entrypoint: 'sh'
#     args : ["-c", "terraform", "-chdir=./cluster-deploy",
#             "apply", "--var-file=<(cat ./cluster-deploy/tfvars/$($BRANCH_NAME).tfvars",
#             "./$($BRANCH_NAME)_common.tfvars)", "--auto-approve"]

#   - id: 'Terraform Application init'
#     name: 'hashicorp/terraform:1.0.0'
#     entrypoint: 'sh'
#     args : ["-c", "terraform", "-chdir=./app-deploy", "init"]
#     name: 'hashicorp/terraform:1.0.0'
#     entrypoint: 'sh'
#     args: 
#     - '-c'
#     - terraform -chdir=./app-deploy init
#   - id: 'Terraform Application set workspace'
#     name: 'hashicorp/terraform:1.0.0'
#     entrypoint: 'sh'
#     args : ["-c", "terraform", "-chdir=./app-deploy", "workspace", "select", "$($BRANCH_NAME)"]
#   - id: 'Terraform Application apply'
#     name: 'hashicorp/terraform:1.0.0'
#     entrypoint: 'sh'
#     args : ["-c", "terraform", "-chdir=./app-deploy", 
#             "apply", "--var-file=<(cat ./app-deploy/tfvars/$($BRANCH_NAME).tfvars", 
#             "./$($BRANCH_NAME)_common.tfvars)", "--auto-approve"]
# options:
#   logging: CLOUD_LOGGING_ONLY