steps:
  - id: 'Terraform Infrastructure'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args: 
    - -c
    - |
      terraform -chdir=./cluster-deploy init
      terraform -chdir=./cluster-deploy workspace select $BRANCH_NAME
      terraform -chdir=./cluster-deploy apply --var-file ./tfvars/${BRANCH_NAME}.tfvars --var-file ../${BRANCH_NAME}_common.tfvars --auto-approve

  - id: 'IP Whitelist'
    name: 'alpine:3.16.2'
    entrypoint: 'sh'
    args:
    - -c
    - |
      pwd
      apk add curl
      echo $(curl -s https://ifconfig.me/ip)/32 > /workspace/ip
      cat /workspace/ip
      gcloud container clusters update dev-hari-poc-tyk-cluster --enable-master-authorized-networks --master-authorized-networks $(cat /workspace/ip)


    
# #*********************#

  - id: 'Terraform Application'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args: 
    - -c
    - |
      terraform -chdir=./app-deploy init
      terraform -chdir=./app-deploy workspace select $BRANCH_NAME
      terraform -chdir=./app-deploy apply --var-file=./tfvars/${BRANCH_NAME}.tfvars  --var-file ../${BRANCH_NAME}_common.tfvars --auto-approve

options:
  logging: CLOUD_LOGGING_ONLY